version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch6
    environment:
      - cluster.name=sv2-cluster623
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=true"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 12g
    volumes:
      - /mnt/data/elasticsearch:/usr/share/elasticsearch/data:rw
      - /var/log/elasticsearch:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
    network_mode: host
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_SECURITY_ENABLED: "false"
    container_name: kibana6
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    network_mode: host
